language: python
 - "3.6"

script:
 - python -m unittest Tests/test_bucketlist.py


install: pip install -r requirements.txt

script:
  nosetests --with-coverage --cover-package=tests && coverage report

